export const RECEPIENAME_UPDATED = "RECEPIENAME_UPDATED"
export const EACHRECIPE_DETAILS = "EACHRECIPE_DETAILS"

export const ADDTOFAVORITES = "ADDTOFAVORITES"

export const BACKDROP_HANDLING = "BACKDROP_HANDLING"
