export const UPDATE_NEW_SEARCHED_RECIPE = "UPDATE_NEW_SEARCHED_RECIPE"
export const UPDATE_SEARCHED_RECIPE_DETAILS = "UPDATE_SEARCHED_RECIPE_DETAILS"

export const UPDATE_FAVORITES_LIST = "UPDATE_FAVORITES_LIST"