export const RECEPIENAME_UPDATED = "RECEPIENAME_UPDATED"
export const EACHRECIPE_DETAILS = "EACHRECIPE_DETAILS"

export const ADDTOFAVORITES = "ADDTOFAVORITES"

export const BACKDROP_HANDLING = "BACKDROP_HANDLING"

export const IS_SIGNEDIN = "IS_SIGNEDIN"
export const AUTH_START = "AUTH_START"
export const AUTH_SUCCESS = "AUTH_SUCCESS"
export const AUTH_FAILED = "AUTH_FAILED"

export const AUTH_LOGOUT = "AUTH_LOGOUT"

export const STORETODATABASE_START = "STORETODATABASE_START"
export const STORETODATABASE_SUCCESS = "STORETODATABASE_SUCCESS"
export const STORETODATABASE_FAILED = "STORETODATABASE_FAILED"